"""Initial migration - add basic ingredient nutritional values

Revision ID: 34a284caeb06
Revises:
Create Date: 2021-04-07 09:08:42.875012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a284caeb06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('carbs', sa.Float(), nullable=True))
    op.add_column('ingredient', sa.Column('energy', sa.Float(), nullable=True))
    op.add_column('ingredient', sa.Column('fats', sa.Float(), nullable=True))
    op.add_column('ingredient', sa.Column('protein', sa.Float(), nullable=True))
    op.add_column('ingredient', sa.Column('salt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'salt')
    op.drop_column('ingredient', 'protein')
    op.drop_column('ingredient', 'fats')
    op.drop_column('ingredient', 'energy')
    op.drop_column('ingredient', 'carbs')
    # ### end Alembic commands ###
